const actions = {
   STORE_CURRENT_USER: "STORE_CURRENT_USER",
   STORE_QUEUED_CARDS: "STORE_QUEUED_CARDS",
   UPDATE_INDEX_OF_CURRENT_CARD: "UPDATE_INDEX_OF_CURRENT_CARDS",
   RESET_QUEUE: "RESET_QUEUE",
   STORE_EDITABLE_CARD: "STORE_EDITABLE_CARD",
};

export default actions;
